// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAASgp2shP-qPW3_NMBWUufeagcThlpQoI',
    appId: '1:59420946637:web:23c84a305449ebb0c8b984',
    messagingSenderId: '59420946637',
    projectId: 'flutterops-3bb0f',
    authDomain: 'flutterops-3bb0f.firebaseapp.com',
    storageBucket: 'flutterops-3bb0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzMgOZFOR2meDBFWCHMacZg49n5wq0Guk',
    appId: '1:59420946637:android:ee8a7822acb4930ac8b984',
    messagingSenderId: '59420946637',
    projectId: 'flutterops-3bb0f',
    storageBucket: 'flutterops-3bb0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uyyNgfYiC-7cnD901G8kSaXR4peY4Vc',
    appId: '1:59420946637:ios:470c102b2cbae1f0c8b984',
    messagingSenderId: '59420946637',
    projectId: 'flutterops-3bb0f',
    storageBucket: 'flutterops-3bb0f.appspot.com',
    iosBundleId: 'com.example.thunderwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8uyyNgfYiC-7cnD901G8kSaXR4peY4Vc',
    appId: '1:59420946637:ios:470c102b2cbae1f0c8b984',
    messagingSenderId: '59420946637',
    projectId: 'flutterops-3bb0f',
    storageBucket: 'flutterops-3bb0f.appspot.com',
    iosBundleId: 'com.example.thunderwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAASgp2shP-qPW3_NMBWUufeagcThlpQoI',
    appId: '1:59420946637:web:fb824e37eaac637ac8b984',
    messagingSenderId: '59420946637',
    projectId: 'flutterops-3bb0f',
    authDomain: 'flutterops-3bb0f.firebaseapp.com',
    storageBucket: 'flutterops-3bb0f.appspot.com',
  );
}
